[workspace]
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge", "https://repo.prefix.dev/rg-forge", "metatensor"]
name = "nebviz"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]

[dependencies]
ira = ">=2.2.0,<3"
eon = ">=2.8.2"
libtorch = ">=2.9,<2.10"

[pypi-dependencies]
rgpycrumbs = "==0.0.5"
ase = ">=3.26.0, <4"
requests = ">=2.28.1, <3"
metatrain = ">=2025.12, <2026"
